### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by sergiocortessat**
Milestone 2. We have added a basic structure to main.rb where the information is displayed and the user can place his name and symbol. This main.rb will be in charge to call the other classes and perform the game

### CODE REVIEW

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: 

**Hi @arikarim and @sergiocortessat **
Please fix your linter issues. And read the [announcement](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)
I am going to mark this project as invalid so when you fix the issue just submit another code review request.
##

 **If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Comment by sergiocortessat** [comment]
Milestone 2. We have added a basic structure to main.rb where the information is displayed and the user can place his name and symbol. This main.rb will be in charge to call the other classes and perform the game

**Review by mke2111 — CHANGES_REQUESTED** [review]
# **🔴 STATUS: CHANGES REQUIRED 🔴 ⚠️** 

## Hey @sergiocortessat & @arikarim, 👋🏽 
 **Thank you for the good job you got going on. The game is starting to take shape and the mockup flow is almost perfect. But we have a few changes to make to get everything right.**

## REQUIRED CHANGES

- [x] The game should tell which players' turn it is (without computing who the winner is). 
- [x] The game asks the player to select from available moves.
- [x] The game informs the player if the selected move is invalid (without computing what an invalid move is).
- [x] The game displays the board after the player move (without computing which spots on the board are taken).
- [x] The game informs the player if the selected move is a winning move (without computing the winning move).
- [x] The game informs the player if the selected move is a draw move (without computing draw).
- [x] The game repeats all actions for the next player's move.
- [x] A loop is needed in this game (recommended is while but anything else will do). This will help implement some of the above requirements.
```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end

```

**Kindly make all the requested changes and submit another CRR. 👍🏽** 

## Cheers!! 🍹 & Happy Coding.

# Reach me on slack for a chitchat 🆘  **Roy Mukuye**

**Comment by sergiocortessat** [comment]
Milestone 2. We have added the structure to main.rb where the information is displayed and the user can place his name and symbol. As well it shows all instructions and steps for the game. This main.rb is in charge to call the other classes and perform the game. Game logic located in game.rb

**Review by arslanbisharat — APPROVED** [review]
# Approved 

Thank you for making changes requested by previous TSE. You have implemented all the changes required for the approval of this project. 

Keep working hard. 

Best 
Arslan Bisharat

**Pull request merged**
